spring.application.name=lab3
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/customer_db
spring.datasource.username=postgres
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=jwt.secret=Lab2CustomerManagementSecretKey2026!@#$%^&*()_+1234567890ABCDEF
jwt.expiration=86400000

logging.level.org.springframework=INFO
logging.level.com.example.customermanagement=DEBUG

spring.artemis.mode=embedded
spring.artemis.embedded.enabled=true
spring.artemis.embedded.persistent=false
spring.artemis.embedded.queues=email.queue,report.queue,customer-notification.queue
spring.artemis.embedded.topics=customer.events.topic

spring.jms.listener.simple.concurrency=1
spring.jms.listener.simple.max-concurrency=5
spring.jms.listener.simple.auto-startup=true

app.queue.email=email.queue
app.queue.report=report.queue
app.queue.customer-notification=customer-notification.queue
app.topic.customer-events=customer.events.topic